# mongo-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
#      nodeSelector:
#       cfke.io/provider: aws
#        topology.kubernetes.io/zone: us-west-2
#
#      You can add these lines to specify node affinity or node selectors if you want to run this on specific nodes in your cluster.
#
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {} #this can be replaced with a persistent volume claim for data persistence. emptyDir is ephemeral and data will be lost if the pod is deleted.

---
# mongo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
